# This is a basic workflow to help you get started with Actions

name: CD

on:
  release:
    types: [ "created" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: go-cross-build
        uses: thatisuday/go-cross-build@v1.1.0
