# This is a basic workflow to help you get started with Actions

name: CD

on:
  release:
    types: [ "created" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: go-cross-build
        uses: thatisuday/go-cross-build@v1.1.0
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          name: 'git-last-branch'
          compress: 'false'
          dest: 'dist'
